#!/bin/bash

# Exit on error
set -e

# Check for src
if [ ! -d "src" ]; then
  echo "Error: src not found. Run ./setup_liggghts.sh first."
  exit 1
fi

# Compile
mkdir -p build
cd build

# Run CMake with specified options
cmake ../src \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr/local \
  -DENABLE_ALL=ON \
  -DENABLE_MODEL_HERTZ=ON \
  -DENABLE_MODEL_SURFACE_DEFAULT=ON \
  -DENABLE_MODEL_SURFACE_SUPERQUAD=ON \
  -DENABLE_MODEL_TANGENTIAL_HISTOR=ON \
  -DENABLE_MPI=ON \
  -DENABLE_SMALLBIG=ON \
  -DENABLE_VTK=ON \
  -DENABLE_JPG=OFF \
  -DENABLE_BIGBIG=OFF \
  -DENABLE_FFMPEG=OFF \
  -DENABLE_GZIP=ON \
  -DENABLE_JPEG=OFF \
  -DENABLE_LONGLONG_TO_LONG=OFF \
  -DENABLE_MODEL_COHESION_EASO_CAP=OFF \
  -DENABLE_MODEL_COHESION_OFF=OFF \
  -DENABLE_MODEL_COHESION_SJKR=OFF \
  -DENABLE_MODEL_COHESION_SJKR2=OFF \
  -DENABLE_MODEL_COHESION_WASHINO_=OFF \
  -DENABLE_MODEL_EDINBURGH=OFF \
  -DENABLE_MODEL_EDINBURGH_STIFFNE=OFF \
  -DENABLE_MODEL_HERTZ=ON \
  -DENABLE_MODEL_HERTZ_STIFFNESS=OFF \
  -DENABLE_MODEL_HOOKE=ON \
  -DENABLE_MODEL_HOOKE_HYSTERESIS=OFF \
  -DENABLE_MODEL_HOOKE_STIFFNESS=OFF \
  -DENABLE_MODEL_LUDING=OFF \
  -DENABLE_MODEL_ROLLING_CDT=OFF \
  -DENABLE_MODEL_ROLLING_EPSD=OFF \
  -DENABLE_MODEL_ROLLING_EPSD2=OFF \
  -DENABLE_MODEL_ROLLING_EPSD3=OFF \
  -DENABLE_MODEL_ROLLING_LUDING=OFF \
  -DENABLE_MODEL_ROLLING_OFF=OFF \
  -DENABLE_MODEL_SURFACE_DEFAULT=ON \
  -DENABLE_MODEL_SURFACE_MULTICONT=OFF \
  -DENABLE_MODEL_SURFACE_SUPERQUAD=ON \
  -DENABLE_MODEL_TANGENTIAL_HISTOR=ON \
  -DENABLE_MODEL_TANGENTIAL_LUDING=OFF \
  -DENABLE_MODEL_TANGENTIAL_NO_HIS=OFF \
  -DENABLE_MODEL_TANGENTIAL_OFF=OFF \
  -DENABLE_MODEL_THORNTON_NING=OFF \
  -DENABLE_MPI=ON \
  -DENABLE_PNG=OFF \
  
# Build the project
make -j$(4)

echo "Build completed successfully!"
