# Global settings
sim_data_dir: "/scratch/$USER"

executable: "./liggghts_source/build/liggghts"
input_script: "./launcher/in.simple_shear_le"

# Simulation parameters
radius: 1
density: 1000

# Sweep parameters
# aspect_ratios: [0.33, 0.4, 0.5, 0.56, 0.67, 0.83, 1.0, 1.2, 1.5, 1.8, 2.0, 2.5, 3.0]
# inertial_numbers: [0.1, 0.046, 0.022, 0.01, 0.0046, 0.0022, 0.001]
# cofs: [0.0, 0.001, 0.01, 0.1, 0.4, 1.0, 10.0]

aspect_ratios: [1.0]
inertial_numbers: [0.1]
cofs: [0.0, 0.4, 10.0]


# Slurm settings
cpus_per_task: 1
ntasks: 10
mem: "4G"
time: "1-00:00:00"
mail_user: "jacopo.bilotto@epfl.ch"
mail_type: "BEGIN,END,FAIL"
